sitename: Generative Mistakes
author: David Omar Flores Chávez
author_url: https://davidomar.com/

description: >
  A collection of interactive experiments in generative artwork and procedural generation.

links:
  - Instagram:
      https://www.instagram.com/davidomarf
  - GitHub:
      https://github.com/davidomarf/generative-mistakes
  - Twitter: 
      https://twitter.com/davidomarf

theme: davidomarf/gart

build_path: public
content_path: sketches
url: /

scripts:
  p5: https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/p5.min.js
  delaunay: https://cdn.jsdelivr.net/npm/delaunator@4.0.1/delaunator.min.js
